### ISSUE TITLE
Doc | Update and complete the doc on how users must generate the `gpg` keys

### ISSUE THREAD

**Issue by exequielrafaela** [binbashar/le-ref-architecture-doc#102]
### What? 
Update and complete the doc on how users must generate the `gpg` keys.

### Why?

* If we leave it free a user can create keys with different configurations. Depending on the version of `gpg` you have, if you run this: `gpg --full-generate-key` you will get different defaults.
* Also, the `gpg` spec can change its defaults and bring us iam user deployment difficulties through our chosen module https://github.com/binbashar/terraform-aws-iam.

### How?

* Defaults can change, so the user will need to generate a **3072 rsa** via arguments that you can specify to use rsa and 3072. As a result it would only remain for the user to provide a name, email and comment (optional) - and passphrase (also optional but highly recommended)

**Comment by exequielrafaela** [comment]
@angelofenoglio @eze-godoy look forward to the doc update using the docker container approach with've discussed through slack. Thanks!

CC: @binbashar/leverage-ref-architecture-aws-dev @binbashar/leverage-ref-architecture-aws-admin

**Comment by angelofenoglio** [comment]
Shall we close this issue @exequielrafaela? As #115 has already been merged I believe we can consider this resolved.

**Comment by exequielrafaela** [comment]
Solved 🚀 

* PR: https://github.com/binbashar/le-ref-architecture-doc/pull/115
* Doc: https://leverage.binbash.com.ar/user-guide/features/identities/gpg/#workaround-for-mac-users

CC: @binbashar/leverage-ref-architecture-aws-dev @binbashar/leverage-ref-architecture-aws-admin
