### ISSUE TITLE
Doc/ update user-guide => Terraform - S3 & DynamoDB for Remote State Storage & Locking section

### ISSUE THREAD

**Issue by exequielrafaela** [binbashar/le-ref-architecture-doc#125]
### What?

Update **tf-backend** initialization with `--skip-validation` where needed.

- https://leverage.binbash.com.ar/first-steps/management-account/#terraform-backend-layer
- https://leverage.binbash.com.ar/first-steps/security-and-shared-accounts/#terraform-backend-layer
- https://leverage.binbash.com.ar/user-guide/ref-architecture-aws/tf-state-workflow/
- https://leverage.binbash.com.ar/user-guide/ref-architecture-aws/tf-state-workflow/#set-up
   - Run `leverage terraform init --skip-validation` 

### Why?

- Cover this specific case to let the user know that they'll need to pass the flag in this scenario.

**Comment by exequielrafaela** [comment]
@juanmatias let's consider the possibility to create another issue to cover:

- https://github.com/gruntwork-io/git-xargs
    - https://github.com/marketplace/actions/enforce-pr-labels

**Comment by juanmatias** [comment]
As per the chat with @angelofenoglio and @rodriguez-matias it is a good idea to add a note when using the skip-validation flag explaining why this is needed.
