### ISSUE TITLE
Enhancement | Add a note on why to use the --skip-validation flag

### ISSUE THREAD

**Issue by juanmatias** [binbashar/le-ref-architecture-doc#135]
## Describe the Enhancement

As per the chat with @angelofenoglio  and @rodriguez-matias  it is a good idea to add a note when using the `--skip-validation` flag explaining why this is needed.

## Expected Behavior

In the documentation should be a note explaining why we are using `--skip-validation` flag when creating backend.

## Use Case

The user following the Leverage guides may wonder why we are skipping the validations when creating the backend.

## Describe Ideal Solution

Add a note explaining why and giving the user the confidence to use the CLI.

## Alternatives Considered

n/a

## Additional Context

When creating the backend layer for first time, the bucket still does not exist. If the Leverage CLI is used with validations it will find the Key does not exist or can not be created. Thus, there's a need of creating first the bucket and then move the `tfstate` file into it using the aforementioned flag.

CC: @exequielrafaela @diego-ojeda-binbash

**Comment by exequielrafaela** [comment]
@juanmatias @angelofenoglio @rodriguez-matias to keep this task simple we could add a link to https://leverage.binbash.com.ar/user-guide/leverage-cli/reference/terraform/#init in the respective entry https://leverage.binbash.com.ar/first-steps/security-and-shared-accounts/

CC: @diego-ojeda-binbash
