### ISSUE TITLE
Feature | Generate new IAM role profiles in AWS configuration files (~/.aws/config)

### ISSUE THREAD

**Issue by marianod92** [binbashar/le-ref-architecture-doc#138]
When a new Role is created in the ref-arch to access AWS accounts, for example, a Developer role, the commands given in this document do not generate the records for that profile/role in the ~/.aws/[PROJECT]/config file.

It would be necessary to evaluate which Roles it would be convenient to allow, taking into account the use cases so that it is as generic as possible.

Also, evaluate what changes would have to be made in the ref-arch to allow the work of these new roles through Terraform that are not always DevOps. For example, some Developers role with less privileges but need to make modifications in a non-productive environment, in non-critical services or require some level of autonomy for their work.

**Comment by exequielrafaela** [comment]
@marianod92 we'll follow-up this task at https://github.com/binbashar/leverage/issues/121
