### ISSUE TITLE
Bug | wrong word in text

### ISSUE THREAD

**Issue by juanmatias** [binbashar/le-ref-architecture-doc#171]
## Describe the Bug
In this [page](https://leverage.binbash.com.ar/first-steps/leverage-project-setup/#next-steps), at the bottom there is this line:

```
Next, you will orchestrate de first and main account of the project, the management account.
```

It should be changed to:

```
Next, you will orchestrate the first and main account of the project, the management account.
```

**Comment by rodriguez-matias** [comment]
this is the current page with the typo
https://leverage.binbash.co/try-leverage/leverage-project-setup/#:~:text=Next%2C%20you%20will%20orchestrate%20de%20first%20and%20main%20account%20of%20the%20project%2C%20the%20management%20account.

**Comment by exequielrafaela** [comment]
Solved with https://github.com/binbashar/le-ref-architecture-doc/pull/197#event-10798580902
