### ISSUE TITLE
Bug | WSL (Windows) workaround to setup / initialize Terraform

### ISSUE THREAD

**Issue by marianod92** [binbashar/le-ref-architecture-doc#174]
## Describe the Bug
Error cloning [le-tf-infra-aws](https://github.com/binbashar/le-tf-infra-aws) repository from Windows WSL environment.
WSL. The _.gitconfig_ is interpreted as a directory by WSL and not as a file.

## Expected Behavior
While it should be able to be initialized in the same way as in Linux/MacOs environments, for now it's enough to add the workaround to the documentation.

## Steps to Reproduce
1. git clone git@github.com:binbashar/le-tf-infra-aws.git

## Screenshots
<img width="850" alt="image" src="https://user-images.githubusercontent.com/35702375/234904880-89522a8f-4acd-4e96-83e5-47b8980c0ce3.png">

## Environment:
 - OS: WSL

## Workaround
```
USER:~/test$ rm -rf /home/USER/.gitconfig/
USER:~/test$ touch /home/USER/.gitconfig
USER:~/test$ cd ..
USER:~$ git clone git@github.com:binbashar/le-tf-infra-aws.git
```

**Comment by exequielrafaela** [comment]
For the moment we're only supporting Linux and MacOS. In case you find the same problem and you want to run Leverage on Windows let us know.
