### ISSUE TITLE
Fix | Documentation fix needed under the "Try Leverage" Create a bootstrap user

### ISSUE THREAD

**Issue by exequielrafaela** [binbashar/le-ref-architecture-doc#186]
# Describe the Bugs

## Bug 1️⃣ 
* Documentation fix needed under the "Try Leverage" section here https://leverage.binbash.co/try-leverage/aws-account-setup/#create-a-bootstrap-user-with-temporary-administrator-permissions  
* Error: It says that it is not necessary to generate AWS IAM keys but when you do the bootstrap it asks for AWS IAM keys since it's actually necessary at this step https://leverage.binbash.co/try-leverage/leverage-project-setup/#configure-bootstrap-credentials when running `leverage credentials configure --type BOOTSTRAP`.

### Screenshots

![image](https://github.com/binbashar/le-ref-architecture-doc/assets/18539704/d5ad5102-3621-46f0-9dbd-124738b4c1b4)

![image](https://github.com/binbashar/le-ref-architecture-doc/assets/18539704/c095973d-0995-4edb-b01a-c2ac9a95cb6b)

---

## Bug 2️⃣ 

👾 **A. Remark the SSO Layer Region specs** 
It is necessary to clarify at the SSO layer configuration (here https://leverage.binbash.co/try-leverage/management-account/#sso-layer) that it is the same AWS Region that in the primary region you've chose during the project creation set in the config, otherwise it throws some errors of `sso:ListInstances` that you do not have permissions.

### Screenshots
![image](https://github.com/binbashar/le-ref-architecture-doc/assets/18539704/39b6a066-557e-4bc9-b550-8741705fcec6)

![image](https://github.com/binbashar/le-ref-architecture-doc/assets/18539704/dc92bb80-6cb3-4217-bb0b-4a7a01d060ea)

<img width="1196" alt="image" src="https://github.com/binbashar/le-ref-architecture-doc/assets/18539704/1e7852bd-c3ab-4a50-bbaf-bc855a1fba4e">

### 📒  NOTES
* Not sure if the AWS Region doesn't match and it has nothing to do with permissions.
* Not sure if the new identity service can only exist in one Region at a time (most probably yes).

👾 **B. Adjust doc steps to avoid hitting yet non existing accounts issue** 
In this same SSO Layer section it is necessary to clarify that at this point it is necessary to only uncomment everything related to the management account exclusively because the other accounts have not been created yet. And on the other hand update the version of the module to `1.1.1` ( here https://github.com/binbashar/le-tf-infra-aws-template/blob/dda848a82296a63819936dd93ead5a1d6d024a96/template/management/global/sso/account_assignments.tf#L12) because otherwise it fails with an api error. And then when we create the other accounts we have to come back here and uncomment the rest of the accounts.

* 📔 **BETTER SOLUTION** as we discussed with @juanmatias and the issue reporter we should review the order in the Doc and move it later so that the SSO code already applies to the accounts that were created.

---

## Bug 3️⃣

Please consider adding information about the regions we recommend to choose during the project creation setup at this step https://leverage.binbash.co/try-leverage/leverage-project-setup/#modify-the-project-definition-file in order to deploy the most cost-effective AWS regions and avoid extra charges.

### AWS Organizations Accounts Regions.
* AWS regions used by accounts will be reviewed and defined according to the most important [factors to consider when choosing an AWS Region](https://binbash.atlassian.net/wiki/external/2159050753/NGZkZWMzMTA5M2UwNDQ0OTk3MjUwMGY5NjA0YzRjNjk?atlOrigin=eyJpIjoiN2Y1NzJkMmZkNGY5NGEyODgwMTkzMjhhYTNiZjVmMDEiLCJwIjoiYyJ9). However, the most common and recommended setup considering costs, features, latency, data transfer speeds, reliability, and availability is:
  * **Primary Region:** `us-east-2 (Ohio)`
  * **Secondary Region:** `us-west-2 (Oregon)`

---

## Bug 4️⃣ 

<img width="1332" alt="image" src="https://github.com/binbashar/le-ref-architecture-doc/assets/18539704/9f8195a6-d014-496d-885b-4c38b312582a">

**Comment by exequielrafaela** [comment]
@juanmatias After solving this issue let's move forward with the Ref Arch fix => update the version of the module to 1.1.1 ( here https://github.com/binbashar/le-tf-infra-aws-template/blob/dda848a82296a63819936dd93ead5a1d6d024a96/template/management/global/sso/account_assignments.tf#L12) because otherwise it fails with an api error

**Comment by rodriguez-matias** [comment]
> https://github.com/binbashar/le-ref-architecture-doc/pull/188

 Bug 2 and Bug 4

**Comment by rodriguez-matias** [comment]
Hello everyone, here you can find the PR related to `BUG 2.B`([bug 2.b](https://github.com/binbashar/le-ref-architecture-doc/issues/186#:~:text=%F0%9F%91%BE%20B.%20Adjust%20doc%20steps%20to%20avoid%20hitting%20yet%20non%20existing%20accounts%20issue)):

https://github.com/binbashar/le-tf-infra-aws/pull/528

**Comment by diego-ojeda-binbash** [comment]
@rodriguez-matias About bug 2.A, I see the PR is ready, right?
@Franr About bug 1 & 3, those should be ready as well, correct?

**Comment by rodriguez-matias** [comment]
> @rodriguez-matias About bug 2.A, I see the PR is ready, right?

Hi @diego-ojeda-binbash , yes 2.A Its already merged here: https://github.com/binbashar/le-ref-architecture-doc/pull/188

**Comment by rodriguez-matias** [comment]
### Issues Summary 

- Bug 1 and Bug 3: ✅  PR: https://github.com/binbashar/le-ref-architecture-doc/pull/187
- Bug 2.A and Bug 4: ✅ PR: https://github.com/binbashar/le-ref-architecture-doc/pull/188
- Bug 2.B: ✅  PR: https://github.com/binbashar/le-tf-infra-aws/pull/528
