### ISSUE TITLE
Feature | "high level path" to show how an end-user would adopt Leverage Reference Architecture

### ISSUE THREAD

**Issue by exequielrafaela** [binbashar/le-ref-architecture-doc#57]
## What?
- **Feature:** Design a "high level path" to show how an end-user would adopt [Leverage Reference Architecture](https://leverage.binbash.com.ar/)
- **Ref link:** Something like this could be useful: https://www.techworld-with-nana.com/devops-bootcamp

## Why?
- Interesting to design a "high level path" in order to adopt Leverage Reference Architecture.
- Should work as guide for possible adopters, like a getting started guide at https://leverage.binbash.com.ar/first-steps/
- Useful to have a simplified view of everything that needs to be done in order to deploy the Leverage Reference Architecture.
- Based on the 1st version of this diagram we should challenge it to reduce, add, simplify, its steps.
- eventually automate some of the steps or make them easier for the Leverage users by means of some tool.

**Comment by exequielrafaela** [comment]
As reviewed with @diego-ojeda-binbash we could consider this reference https://www.binbash.com.ar/leverage for the leverage.binbash.com.ar we both agree that having a short presentation video on the main header section of the doc homepage would be very useful and clarifying for a new adopter / user / customer.

CC: @juanmatias

**Comment by diego-ojeda-binbash** [comment]
UPDATE: @juanmatias created the following playbooks https://leverage.binbash.co/user-guide/playbooks/ which could contribute to the purpose of this ticket.

**Comment by exequielrafaela** [comment]
+ @juanmatias considerably improved the try-leverage sections => https://github.com/binbashar/le-ref-architecture-doc/pull/202
