### ISSUE TITLE
Feature | Remove Terraform layer warning in First Steps guide

### ISSUE THREAD

**Issue by angelofenoglio** [binbashar/le-ref-architecture-doc#88]
## Describe the Feature

Remove warnings in Terraform layer deployment explanation when bug is confirmed to be fixed.

**Comment by exequielrafaela** [comment]
@angelofenoglio I think we've already addressed this issue right?

**Comment by angelofenoglio** [comment]
@exequielrafaela I guess it is. Regardless, it is really ill defined.
I'll close it for now.
When something specific shows up we can create a dedicated issue.
