### ISSUE TITLE
Bug | Broken Links in Documentacion

### ISSUE THREAD

**Issue by Rodriguez-Matias** [binbashar/le-ref-architecture-doc#94]
## What?
Found some **Broken Links** (error 404) for the Binbash Leverage Reference Documentation.

## Where?
URL: [https://leverage.binbash.com.ar/first-steps/introduction/](https://leverage.binbash.com.ar/first-steps/introduction/)

The following links were broken:
- 	BROKEN: link https://leverage.binbash.com.ar/first-steps/how-it-works/

	
       ![image](https://user-images.githubusercontent.com/65817386/135019791-edac4f63-e060-4e5d-bba4-369036fbc1cc.png)

----
URL: [https://leverage.binbash.com.ar/first-steps/aws-account-setup/](https://leverage.binbash.com.ar/first-steps/aws-account-setup/)

The following links were broken:
- 	BROKEN: link https://leverage.binbash.com.ar/first-steps/user-guide/organization/organization-init#user-guide

	
    ![image](https://user-images.githubusercontent.com/65817386/135019911-d7565461-7ca9-40f2-b308-0d01eac22436.png)

----
URL: [https://leverage.binbash.com.ar/first-steps/leverage-project-setup/](https://leverage.binbash.com.ar/first-steps/leverage-project-setup/)
The following links were broken:
- 	BROKEN: link https://leverage.binbash.com.ar/first-steps/user-guide/base-workflow/leverage-cli/reference/project#init
- 	BROKEN: link https://leverage.binbash.com.ar/first-steps/user-guide/base-workflow/leverage-cli/reference/credentials#create
- 	BROKEN: link https://leverage.binbash.com.ar/first-steps/user-guide/base-workflow/leverage-cli/reference/project#create

	
    ![image](https://user-images.githubusercontent.com/65817386/135019954-5bb38b2b-7ade-453c-99c4-67bd12439979.png)

----
URL: [https://leverage.binbash.com.ar/first-steps/management-account/](https://leverage.binbash.com.ar/first-steps/management-account/)

The following links were broken:
- 	BROKEN: link https://leverage.binbash.com.ar/first-steps/user-guide/base-workflow/leverage-cli/reference/terraform#init
- 	BROKEN: link https://leverage.binbash.com.ar/first-steps/user-guide/base-workflow/leverage-cli/reference/terraform#apply
- 	BROKEN: link https://leverage.binbash.com.ar/first-steps/user-guide/identities/gpg/
- 	BROKEN: link https://leverage.binbash.com.ar/first-steps/user-guide/base-workflow/leverage-cli/reference/terraform#import
- 	BROKEN: link https://leverage.binbash.com.ar/first-steps/user-guide/base-workflow/leverage-cli/reference/credentials#update

	
    ![image](https://user-images.githubusercontent.com/65817386/135019971-6403b539-51aa-4391-b516-647ef68c455c.png)

----
URL: [https://leverage.binbash.com.ar/first-steps/post-deployment/](https://leverage.binbash.com.ar/first-steps/post-deployment/)

The following links were broken:
- 	BROKEN: link https://leverage.binbash.com.ar/first-steps/first-steps/management-account/#identities-layer
- 	BROKEN: link https://leverage.binbash.com.ar/first-steps/first-steps/security-and-shared-accounts/#identities-layer
- 	BROKEN: link https://leverage.binbash.com.ar/first-steps/user-guide/identities/gpg#how-to-manage-your-gpg-keys

    ![image](https://user-images.githubusercontent.com/65817386/135019981-a30a0932-cc5d-40d9-8ece-1f6b299ab05b.png)

	

## Proposed Solution

Its seems like the links related with the user-guide section don’t wok correctly. 
I think the problem cloud be in the "href",  it's points to a nonexistent path:

- **Now:** 

	`<a href="../../user-guide/identities/gpg/" class="md-nav__link">`

- **Should be:**

	` <a href="../../../user-guide/identities/gpg/" class="md-nav__link">`

Line 2157 of le-ref-architecture-doc/first-steps/management-account/index.html

![image](https://user-images.githubusercontent.com/65817386/135019991-ab7fddd3-5f4a-4c34-b6d1-5c8bfdab1f62.png)

**Comment by exequielrafaela** [comment]
@Rodriguez-Matias Thanks for reporting this issue, it has a very clear and complete explanation. So as discussed we'll work together on order to solve it 🚀 

CC: @binbashar/leverage-ref-architecture-aws-admin @binbashar/leverage-ref-architecture-aws-dev

**Comment by exequielrafaela** [comment]
@Rodriguez-Matias thanks for your contribution here, as we've seen after sync with master branch and re-deploying everything works fine. 

CC: @binbashar/leverage-ref-architecture-aws-admin @binbashar/leverage-ref-architecture-aws-dev
