### ISSUE TITLE
Bug | GPG key with errors created by MacBook users

### ISSUE THREAD

**Issue by rodriguez-matias** [binbashar/le-ref-architecture-doc#99]
# Bug | GPG key with errors created by MacBook users

## What?

Following the First Steps to deploy BInbash-Leverage  found some issue when I create the **GPG keys** in my local machine (*MacBook - macOS v10.15*)

After I generate the gpg keys for the user *natasha.romanoff*, the command `$ leverage terraform apply` returns an error:

![gpg-error-002](https://user-images.githubusercontent.com/65817386/137025947-363a7df2-eb79-462e-9369-fe07789c32e2.png)

## Where?

First Steps secction in the step Orchestrate the Management account --> Identities layer --> base-identities directory

[https://leverage.binbash.com.ar/first-steps/management-account/#identities-layer](https://leverage.binbash.com.ar/first-steps/management-account/#identities-layer)

---

## Possible workaround

Following the recommendation of the binbash community support team, a possible solution could be: Generate the GPG keys in a Linux Virtual Machine and then import them to the local MacBook:

**Example steps from EC2 instance (linux vm):**
1. Lunch an EC2 instance (linux) and Connect to it:
`ssh -i .../AWS/KeyPairs/ec2KeyPair.pem ec2-user@ec2-52-23-179-198.compute-1.amazonaws.com` 

1. Generate the Keys:
`$ gpg --gen-key `

1. Verify Private and Public Keys in remote linux VM :
`$ gpg --list-secret-keys`	; `$ gpg --list-keys`

1. Export the keys to a file so that it can be transferred to the local machine:  `$ gpg --export-secret-keys natasha.romanoff > natasha_romanoff_private.key `

1. From the local computer: Copy the keys from the EC2 instance to the local computer: 

	`scp -i .../AWS/KeyPairs/ec2KeyPair.pem ec2-user@ec2-54-81-226-212.compute-1.amazonaws.com:/home/ec2-user/*.key /Users/LocalUser/Desktop/imported-ec2-keys`

1. Import the private keys on the local machine: `$ gpg --import natasha.romanoff_private.key`

1. Verify on the local computer that the Public and Private keys are loaded correctly: `$ gpg --list-secret-keys` ;  `$ gpg --list-keys`

1. Now you should run again correctly: `$ gpg --export natasha.romanoff | base64 > natasha.romanoff` and `$ leverage terraform apply`

   ![gpg-solution-002](https://user-images.githubusercontent.com/65817386/137025976-90dd4d13-91d9-4ca0-9c1d-a0cf59ae79b1.png)

**Comment by exequielrafaela** [comment]
@angelofenoglio @eze-godoy when completing https://github.com/binbashar/le-ref-architecture-doc/issues/102 I think we'll cover this issue. But please let's have any important considerations for the doc related to mac users gpg key generation. Thanks.

**Comment by angelofenoglio** [comment]
Shall we close this issue @exequielrafaela? As #115 has already been merged I believe we can consider this resolved.

**Comment by exequielrafaela** [comment]
Solved 🚀 

* PR: https://github.com/binbashar/le-ref-architecture-doc/pull/115
* Doc: https://leverage.binbash.com.ar/user-guide/features/identities/gpg/#workaround-for-mac-users

CC: @binbashar/leverage-ref-architecture-aws-dev @binbashar/leverage-ref-architecture-aws-admin
